[[news]]
date = "2026-09"
content = "Started my PhD in Computer and Information Science at the University of Pennsylvania."

[[news]]
date = "2026-07"
content = "MathDuels was accepted to COLM 2026."
